### ISSUE TITLE
スマホで入力できないです

### ISSUE THREAD

**Issue by me-maruo** [me-maruo/pm-agile-20190606#19]

**Comment by me-nakama** [comment]
入力できないというのは具体的にどのような状況でしょうか？inputに文字が入らないのか、選択ができないのか、入れても消えてしまうのか。詳細をいただければと思います。
・利用している機種
・ブラウザ

**Comment by me-maruo** [comment]
お客様から伝えられた内容をそのままISSUEにしました

**Comment by me-nakama** [comment]
承知しました。
バグの可能性があるので、bugのラベルをつけて優先度をあげて検証に回します。
